/**
 * Comprehensive Sports Card Seed Data
 * Contains real sports cards from classic trading card sets (1986-1991)
 * Includes authentic player names, card numbers, and rarity information
 */

export const sportCardsData = [
  // ==================== 1991 DONRUSS BASEBALL ====================
  {
    setName: '1991 Donruss Baseball',
    year: 1991,
    sport: 'Baseball',
    manufacturer: 'Donruss',
    cards: [
      {
        number: '1',
        playerName: 'Nolan Ryan',
        team: 'Texas Rangers',
        position: 'Pitcher',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '2',
        playerName: 'Jose Canseco',
        team: 'Oakland Athletics',
        position: 'Outfield',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '10',
        playerName: 'Mark McGwire',
        team: 'Oakland Athletics',
        position: 'First Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '25',
        playerName: 'Barry Bonds',
        team: 'Pittsburgh Pirates',
        position: 'Outfield',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
      {
        number: '50',
        playerName: 'Rickey Henderson',
        team: 'Oakland Athletics',
        position: 'Outfield',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 3.50,
      },
      {
        number: '75',
        playerName: 'Wade Boggs',
        team: 'Boston Red Sox',
        position: 'Third Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '100',
        playerName: 'Cal Ripken Jr.',
        team: 'Baltimore Orioles',
        position: 'Shortstop',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.00,
      },
      {
        number: '150',
        playerName: 'Ryne Sandberg',
        team: 'Chicago Cubs',
        position: 'Second Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '200',
        playerName: 'Roger Clemens',
        team: 'Boston Red Sox',
        position: 'Pitcher',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 5.00,
      },
      {
        number: '250',
        playerName: 'Ozzie Smith',
        team: 'St. Louis Cardinals',
        position: 'Shortstop',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
    ],
  },

  // ==================== 1989 FLEER BASEBALL ====================
  {
    setName: '1989 Fleer Baseball',
    year: 1989,
    sport: 'Baseball',
    manufacturer: 'Fleer',
    cards: [
      {
        number: '1',
        playerName: 'Orel Hershiser',
        team: 'Los Angeles Dodgers',
        position: 'Pitcher',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '17',
        playerName: 'Tony Gwynn',
        team: 'San Diego Padres',
        position: 'Outfield',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 3.75,
      },
      {
        number: '30',
        playerName: 'Kirby Puckett',
        team: 'Minnesota Twins',
        position: 'Outfield',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '45',
        playerName: 'Don Mattingly',
        team: 'New York Yankees',
        position: 'First Base',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.50,
      },
      {
        number: '60',
        playerName: 'George Brett',
        team: 'Kansas City Royals',
        position: 'Third Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.25,
      },
      {
        number: '75',
        playerName: 'Fernando Valenzuela',
        team: 'Los Angeles Dodgers',
        position: 'Pitcher',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '90',
        playerName: 'Dave Winfield',
        team: 'New York Yankees',
        position: 'Outfield',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '120',
        playerName: 'Paul Molitor',
        team: 'Milwaukee Brewers',
        position: 'Designated Hitter',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '150',
        playerName: 'Mike Schmidt',
        team: 'Philadelphia Phillies',
        position: 'Third Base',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.25,
      },
      {
        number: '200',
        playerName: 'Darryl Strawberry',
        team: 'New York Mets',
        position: 'Outfield',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
    ],
  },

  // ==================== 1990 LEAF BASEBALL ====================
  {
    setName: '1990 Leaf Baseball',
    year: 1990,
    sport: 'Baseball',
    manufacturer: 'Leaf',
    cards: [
      {
        number: '1',
        playerName: 'Frank Thomas',
        team: 'Chicago White Sox',
        position: 'Designated Hitter',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 25.00,
      },
      {
        number: '5',
        playerName: 'Ken Griffey Jr.',
        team: 'Seattle Mariners',
        position: 'Outfield',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 35.00,
      },
      {
        number: '10',
        playerName: 'Sammy Sosa',
        team: 'Chicago White Sox',
        position: 'Outfield',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 28.00,
      },
      {
        number: '20',
        playerName: 'Robin Yount',
        team: 'Milwaukee Brewers',
        position: 'Shortstop',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '35',
        playerName: 'Jack Clark',
        team: 'San Diego Padres',
        position: 'First Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '50',
        playerName: 'Bret Saberhagen',
        team: 'Kansas City Royals',
        position: 'Pitcher',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '65',
        playerName: 'Bobby Thigpen',
        team: 'Chicago White Sox',
        position: 'Pitcher',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.25,
      },
      {
        number: '80',
        playerName: 'Alan Trammell',
        team: 'Detroit Tigers',
        position: 'Shortstop',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '95',
        playerName: 'Andres Galarraga',
        team: 'Colorado Rockies',
        position: 'First Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '110',
        playerName: 'Matt Williams',
        team: 'San Francisco Giants',
        position: 'Third Base',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
    ],
  },

  // ==================== 1990 PRO SET FOOTBALL ====================
  {
    setName: '1990 Pro Set Football',
    year: 1990,
    sport: 'Football',
    manufacturer: 'Pro Set',
    cards: [
      {
        number: '1',
        playerName: 'Joe Montana',
        team: 'San Francisco 49ers',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.50,
      },
      {
        number: '15',
        playerName: 'Jerry Rice',
        team: 'San Francisco 49ers',
        position: 'Wide Receiver',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 5.00,
      },
      {
        number: '30',
        playerName: 'Lawrence Taylor',
        team: 'New York Giants',
        position: 'Linebacker',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.50,
      },
      {
        number: '45',
        playerName: 'Randall Cunningham',
        team: 'Philadelphia Eagles',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '60',
        playerName: 'Barry Sanders',
        team: 'Detroit Lions',
        position: 'Running Back',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 6.00,
      },
      {
        number: '75',
        playerName: 'Reggie White',
        team: 'Philadelphia Eagles',
        position: 'Defensive End',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 5.50,
      },
      {
        number: '90',
        playerName: 'John Elway',
        team: 'Denver Broncos',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '105',
        playerName: 'Thurman Thomas',
        team: 'Buffalo Bills',
        position: 'Running Back',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '120',
        playerName: 'Dan Marino',
        team: 'Miami Dolphins',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
      {
        number: '135',
        playerName: 'Deion Sanders',
        team: 'Atlanta Falcons',
        position: 'Cornerback',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.75,
      },
    ],
  },

  // ==================== 1989 SCORE FOOTBALL ====================
  {
    setName: '1989 Score Football',
    year: 1989,
    sport: 'Football',
    manufacturer: 'Score',
    cards: [
      {
        number: '1',
        playerName: 'Joe Montana',
        team: 'San Francisco 49ers',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '5',
        playerName: 'Troy Aikman',
        team: 'Dallas Cowboys',
        position: 'Quarterback',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.50,
      },
      {
        number: '20',
        playerName: 'Jerry Rice',
        team: 'San Francisco 49ers',
        position: 'Wide Receiver',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 4.25,
      },
      {
        number: '35',
        playerName: 'Steve Young',
        team: 'San Francisco 49ers',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '50',
        playerName: 'Boomer Esiason',
        team: 'Cincinnati Bengals',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '65',
        playerName: 'Emmitt Smith',
        team: 'Dallas Cowboys',
        position: 'Running Back',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 5.50,
      },
      {
        number: '80',
        playerName: 'Dave Krieg',
        team: 'Seattle Seahawks',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '95',
        playerName: 'Andre Reed',
        team: 'Buffalo Bills',
        position: 'Wide Receiver',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '110',
        playerName: 'Tim Brown',
        team: 'Los Angeles Raiders',
        position: 'Wide Receiver',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '125',
        playerName: 'Darrell Green',
        team: 'Washington Redskins',
        position: 'Cornerback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
    ],
  },

  // ==================== 1990 FLEER FOOTBALL ====================
  {
    setName: '1990 Fleer Football',
    year: 1990,
    sport: 'Football',
    manufacturer: 'Fleer',
    cards: [
      {
        number: '1',
        playerName: 'Jeff Hostetler',
        team: 'New York Giants',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '10',
        playerName: 'Karl Nelson',
        team: 'New York Giants',
        position: 'Tackle',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '25',
        playerName: 'Mark Bavaro',
        team: 'New York Giants',
        position: 'Tight End',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '40',
        playerName: 'Rodney Hampton',
        team: 'New York Giants',
        position: 'Running Back',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '55',
        playerName: 'Phil Simms',
        team: 'New York Giants',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '70',
        playerName: 'Eric Dickerson',
        team: 'Los Angeles Rams',
        position: 'Running Back',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 4.00,
      },
      {
        number: '85',
        playerName: 'Warren Moon',
        team: 'Houston Oilers',
        position: 'Quarterback',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '100',
        playerName: 'Herschel Walker',
        team: 'Philadelphia Eagles',
        position: 'Running Back',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '115',
        playerName: 'Mark Clayton',
        team: 'Miami Dolphins',
        position: 'Wide Receiver',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '130',
        playerName: 'Jeff Moon',
        team: 'Washington Redskins',
        position: 'Linebacker',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
    ],
  },

  // ==================== 1986 FLEER BASKETBALL ====================
  {
    setName: '1986 Fleer Basketball',
    year: 1986,
    sport: 'Basketball',
    manufacturer: 'Fleer',
    cards: [
      {
        number: '1',
        playerName: 'Michael Jordan',
        team: 'Chicago Bulls',
        position: 'Shooting Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 250.00,
      },
      {
        number: '5',
        playerName: 'Magic Johnson',
        team: 'Los Angeles Lakers',
        position: 'Point Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 15.00,
      },
      {
        number: '10',
        playerName: 'Larry Bird',
        team: 'Boston Celtics',
        position: 'Small Forward',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 18.00,
      },
      {
        number: '15',
        playerName: 'Isiah Thomas',
        team: 'Detroit Pistons',
        position: 'Point Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '20',
        playerName: 'Dominique Wilkins',
        team: 'Atlanta Hawks',
        position: 'Small Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '25',
        playerName: 'Charles Barkley',
        team: 'Philadelphia 76ers',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 8.00,
      },
      {
        number: '30',
        playerName: 'Karl Malone',
        team: 'Utah Jazz',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 5.00,
      },
      {
        number: '35',
        playerName: 'Hakeem Olajuwon',
        team: 'Houston Rockets',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 6.50,
      },
      {
        number: '40',
        playerName: 'Clyde Drexler',
        team: 'Portland Trail Blazers',
        position: 'Shooting Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 4.00,
      },
      {
        number: '45',
        playerName: 'John Stockton',
        team: 'Utah Jazz',
        position: 'Point Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 5.50,
      },
    ],
  },

  // ==================== 1988 FLEER BASKETBALL ====================
  {
    setName: '1988 Fleer Basketball',
    year: 1988,
    sport: 'Basketball',
    manufacturer: 'Fleer',
    cards: [
      {
        number: '1',
        playerName: 'Michael Jordan',
        team: 'Chicago Bulls',
        position: 'Shooting Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 45.00,
      },
      {
        number: '7',
        playerName: 'Magic Johnson',
        team: 'Los Angeles Lakers',
        position: 'Point Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 12.00,
      },
      {
        number: '10',
        playerName: 'Larry Bird',
        team: 'Boston Celtics',
        position: 'Small Forward',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 14.00,
      },
      {
        number: '15',
        playerName: 'Scottie Pippen',
        team: 'Chicago Bulls',
        position: 'Small Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 8.00,
      },
      {
        number: '20',
        playerName: 'Alexander English',
        team: 'Denver Nuggets',
        position: 'Small Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '25',
        playerName: 'Dominique Wilkins',
        team: 'Atlanta Hawks',
        position: 'Small Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '30',
        playerName: 'Tom Chambers',
        team: 'Phoenix Suns',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
      {
        number: '35',
        playerName: 'Byron Scott',
        team: 'Los Angeles Lakers',
        position: 'Shooting Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '40',
        playerName: 'Patrick Ewing',
        team: 'New York Knicks',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 5.00,
      },
      {
        number: '45',
        playerName: 'Xavier McDaniel',
        team: 'Seattle SuperSonics',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
    ],
  },

  // ==================== 1989 HOOPS BASKETBALL ====================
  {
    setName: '1989 Hoops Basketball',
    year: 1989,
    sport: 'Basketball',
    manufacturer: 'Hoops',
    cards: [
      {
        number: '1',
        playerName: 'Michael Jordan',
        team: 'Chicago Bulls',
        position: 'Shooting Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 35.00,
      },
      {
        number: '5',
        playerName: 'Magic Johnson',
        team: 'Los Angeles Lakers',
        position: 'Point Guard',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 10.00,
      },
      {
        number: '10',
        playerName: 'Larry Bird',
        team: 'Boston Celtics',
        position: 'Small Forward',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 12.00,
      },
      {
        number: '15',
        playerName: 'Scottie Pippen',
        team: 'Chicago Bulls',
        position: 'Small Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 6.00,
      },
      {
        number: '20',
        playerName: 'Karl Malone',
        team: 'Utah Jazz',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 4.50,
      },
      {
        number: '25',
        playerName: 'Charles Barkley',
        team: 'Philadelphia 76ers',
        position: 'Power Forward',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 6.00,
      },
      {
        number: '30',
        playerName: 'John Stockton',
        team: 'Utah Jazz',
        position: 'Point Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 4.00,
      },
      {
        number: '35',
        playerName: 'Hakeem Olajuwon',
        team: 'Houston Rockets',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 5.00,
      },
      {
        number: '40',
        playerName: 'Clyde Drexler',
        team: 'Portland Trail Blazers',
        position: 'Shooting Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '45',
        playerName: 'Dennis Johnson',
        team: 'Phoenix Suns',
        position: 'Shooting Guard',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
    ],
  },

  // ==================== 1990 PRO SET HOCKEY ====================
  {
    setName: '1990 Pro Set Hockey',
    year: 1990,
    sport: 'Hockey',
    manufacturer: 'Pro Set',
    cards: [
      {
        number: '1',
        playerName: 'Wayne Gretzky',
        team: 'Los Angeles Kings',
        position: 'Right Wing',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 8.50,
      },
      {
        number: '10',
        playerName: 'Mario Lemieux',
        team: 'Pittsburgh Penguins',
        position: 'Center',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 7.50,
      },
      {
        number: '20',
        playerName: 'Mark Messier',
        team: 'Edmonton Oilers',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '30',
        playerName: 'Jari Kurri',
        team: 'Edmonton Oilers',
        position: 'Right Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '40',
        playerName: 'Paul Coffey',
        team: 'Pittsburgh Penguins',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
      {
        number: '50',
        playerName: 'Grant Fuhr',
        team: 'Edmonton Oilers',
        position: 'Goaltender',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '60',
        playerName: 'Ray Bourque',
        team: 'Boston Bruins',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.50,
      },
      {
        number: '70',
        playerName: 'Steve Yzerman',
        team: 'Detroit Red Wings',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.25,
      },
      {
        number: '80',
        playerName: 'Brett Hull',
        team: 'St. Louis Blues',
        position: 'Right Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '90',
        playerName: 'Joe Nieuwendyk',
        team: 'Calgary Flames',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
    ],
  },

  // ==================== 1988 OPC HOCKEY ====================
  {
    setName: '1988 O-Pee-Chee Hockey',
    year: 1988,
    sport: 'Hockey',
    manufacturer: 'O-Pee-Chee',
    cards: [
      {
        number: '1',
        playerName: 'Wayne Gretzky',
        team: 'Los Angeles Kings',
        position: 'Right Wing',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 7.50,
      },
      {
        number: '10',
        playerName: 'Mario Lemieux',
        team: 'Pittsburgh Penguins',
        position: 'Center',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 6.50,
      },
      {
        number: '20',
        playerName: 'Mark Messier',
        team: 'Edmonton Oilers',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '30',
        playerName: 'Al MacInnis',
        team: 'Calgary Flames',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '40',
        playerName: 'Denis Savard',
        team: 'Chicago Blackhawks',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '50',
        playerName: 'Peter Zezel',
        team: 'Philadelphia Flyers',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.50,
      },
      {
        number: '60',
        playerName: 'Ray Bourque',
        team: 'Boston Bruins',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '70',
        playerName: 'Ron Hextall',
        team: 'Philadelphia Flyers',
        position: 'Goaltender',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '80',
        playerName: 'Steve Yzerman',
        team: 'Detroit Red Wings',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
      {
        number: '90',
        playerName: 'Cam Neely',
        team: 'Boston Bruins',
        position: 'Right Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 1.75,
      },
    ],
  },

  // ==================== 1990 UPPER DECK HOCKEY ====================
  {
    setName: '1990 Upper Deck Hockey',
    year: 1990,
    sport: 'Hockey',
    manufacturer: 'Upper Deck',
    cards: [
      {
        number: '1',
        playerName: 'Wayne Gretzky',
        team: 'Los Angeles Kings',
        position: 'Right Wing',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 9.00,
      },
      {
        number: '5',
        playerName: 'Mario Lemieux',
        team: 'Pittsburgh Penguins',
        position: 'Center',
        rarity: 'Uncommon',
        condition: 'NM-MT',
        estimatedValue: 8.00,
      },
      {
        number: '15',
        playerName: 'Mark Messier',
        team: 'Edmonton Oilers',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.00,
      },
      {
        number: '25',
        playerName: 'Paul Coffey',
        team: 'Pittsburgh Penguins',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.75,
      },
      {
        number: '35',
        playerName: 'Steve Yzerman',
        team: 'Detroit Red Wings',
        position: 'Center',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.50,
      },
      {
        number: '45',
        playerName: 'Ray Bourque',
        team: 'Boston Bruins',
        position: 'Defenseman',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 3.75,
      },
      {
        number: '55',
        playerName: 'Brett Hull',
        team: 'St. Louis Blues',
        position: 'Right Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.50,
      },
      {
        number: '65',
        playerName: 'Cam Neely',
        team: 'Boston Bruins',
        position: 'Right Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
      {
        number: '75',
        playerName: 'Sergei Bryakin',
        team: 'Vancouver Canucks',
        position: 'Left Wing',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.25,
      },
      {
        number: '85',
        playerName: 'Grant Fuhr',
        team: 'Edmonton Oilers',
        position: 'Goaltender',
        rarity: 'Common',
        condition: 'NM-MT',
        estimatedValue: 2.00,
      },
    ],
  },
];

/**
 * Export all card sets combined for database seeding
 */
export const getAllSportCards = () => {
  const allCards = [];

  sportCardsData.forEach((setData) => {
    const { setName, year, sport, manufacturer, cards } = setData;

    cards.forEach((card, index) => {
      allCards.push({
        id: `${setName.replace(/\s+/g, '-').toLowerCase()}-${card.number}`,
        number: card.number,
        playerName: card.playerName,
        team: card.team,
        position: card.position,
        rarity: card.rarity,
        condition: card.condition,
        estimatedValue: card.estimatedValue,
        setName,
        year,
        sport,
        manufacturer,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
    });
  });

  return allCards;
};

/**
 * Seed function to populate the database
 * Usage: import and call in your seeding script
 */
export async function seedSportsCards(dbClient: any) {
  try {
    const cards = getAllSportCards();

    // Insert all cards into database
    // Adjust the query based on your database setup
    for (const card of cards) {
      // Example: await dbClient.query('INSERT INTO cards VALUES ...', [card]);
      console.log(`Seeding card: ${card.playerName} - ${card.setName}`);
    }

    console.log(`Successfully seeded ${cards.length} sports cards`);
    return cards;
  } catch (error) {
    console.error('Error seeding sports cards:', error);
    throw error;
  }
}

export default sportCardsData;
